import { NextRequest, NextResponse } from "next/server";
import { batchScoreEmail } from "@/lib/langfuse/scoring";

/**
 * API endpoint to evaluate and score email quality
 * 
 * This allows you to manually score emails generated by the system,
 * or integrate with automated evaluation systems.
 * 
 * Example usage:
 * POST /api/evaluate-email
 * {
 *   "traceId": "trace-id-from-langfuse",
 *   "scores": {
 *     "quality": 0.8,
 *     "personalization": 0.9,
 *     "professionalTone": 0.85
 *   },
 *   "comment": "Good email with relevant research"
 * }
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { traceId, scores, comment } = body;

    if (!traceId || typeof traceId !== "string") {
      return NextResponse.json(
        { error: "Missing or invalid traceId" },
        { status: 400 }
      );
    }

    if (!scores || typeof scores !== "object") {
      return NextResponse.json(
        { error: "Missing or invalid scores object" },
        { status: 400 }
      );
    }

    // Validate score values (must be between 0 and 1)
    const validScores: {
      quality?: number;
      personalization?: number;
      professionalTone?: number;
    } = {};

    if (scores.quality !== undefined) {
      const quality = Number(scores.quality);
      if (isNaN(quality) || quality < 0 || quality > 1) {
        return NextResponse.json(
          { error: "Quality score must be between 0 and 1" },
          { status: 400 }
        );
      }
      validScores.quality = quality;
    }

    if (scores.personalization !== undefined) {
      const personalization = Number(scores.personalization);
      if (isNaN(personalization) || personalization < 0 || personalization > 1) {
        return NextResponse.json(
          { error: "Personalization score must be between 0 and 1" },
          { status: 400 }
        );
      }
      validScores.personalization = personalization;
    }

    if (scores.professionalTone !== undefined) {
      const professionalTone = Number(scores.professionalTone);
      if (isNaN(professionalTone) || professionalTone < 0 || professionalTone > 1) {
        return NextResponse.json(
          { error: "Professional tone score must be between 0 and 1" },
          { status: 400 }
        );
      }
      validScores.professionalTone = professionalTone;
    }

    if (Object.keys(validScores).length === 0) {
      return NextResponse.json(
        { error: "At least one valid score must be provided" },
        { status: 400 }
      );
    }

    await batchScoreEmail({
      traceId,
      scores: validScores,
      comment: typeof comment === "string" ? comment : undefined,
    });

    return NextResponse.json({
      success: true,
      traceId,
      scores: validScores,
    });
  } catch (error) {
    console.error("Email evaluation error:", error);
    const message = error instanceof Error ? error.message : "Failed to evaluate email";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export function GET() {
  return NextResponse.json({ error: "Method not allowed" }, { status: 405 });
}


